package conhash

import "bytes"

// HIDComp is a less than comparison function for []byte generated by crypto/sha1
// this function is used in SortedMap.New()
func HIDComp(i, j interface{}) bool {
	return (bytes.Compare(i.([]byte), j.([]byte)) <= 0)
}
